[project]
name = "concall-parser"
version = "1.0.4"
description = "A parser for extracting analyst discussion and management commentary efficiently from concalls."
authors = [
    { name = "Jay Shah", email = "jayshah0726@gmail.com" },
    { name = "Pranshu Raj", email = "pranshuraj65536@gmail.com" },
]
maintainers = [{ name = "Pranshu Raj", email = "pranshuraj65536@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "groq==0.22.0",
    "pdfplumber==0.11.5",
    "python-dotenv==1.1.0",
    "requests==2.32.2",
]

[project.optional-dependencies]
dev = ["ruff==0.4.1", "pre-commit==3.7.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["concall_parser"]

[tool.ruff]
line-length = 80
indent-width = 4
target-version = "py310"
extend-exclude = ["__init__.py", "migrations"]

[tool.ruff.lint]
extend-select = [
    "UP", # pyupgrade
    "E",  # pycodestyle
    "I",  # isort
    "D",  # pydocstyle
]

ignore = [
    "D100", # undocumented-public-module
    "D104", # undocumented-public-package
    "D106", # undocumented-public-nested-class
    "D107", # undocumented-public-init
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-line-length = 100

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
