name: Publish to PyPI

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    name: Build and publish on PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build twine requests

      - name: Bump version using script
        id: bump_version
        run: python .github/scripts/update_version.py ${{ github.event.inputs.bump_type }}

      - name: Commit and push new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "CI: bump version to ${{ steps.bump_version.outputs.new_version }}"
          git tag v${{ steps.bump_version.outputs.new_version }}
          git push origin main --tags

      - name: Build the package
        run: python -m build

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
